jobs:
  -
    job: '${{ parameters.name }}'
    timeoutInMinutes: 0
    pool:
      vmImage: '${{ parameters.image }}'
    variables:
      CI: true
    steps:
      -
        script: 'go get -u -v github.com/therecipe/qt/cmd/... && $(go env GOPATH)/bin/qtsetup'
